### ISSUE TITLE
to-do list for all

### ISSUE THREAD

**Issue by itchyshin** [itchyshin/publication_bias#1]
Things to be finished before submission

### Figures
- [x] Figure 1 (SE, V, 1/SE, 1/V) = @mlagisz 
- [x] Figure 2  (Survey) = @roseodea 
- [x] Figure 3 (Funnel) = @itchyshin 
- [x] Figure 4 (Egger) = @itchyshin 
- [x] Figure 5 (P + Selection) = @itchyshin 
- [x] Figure 6 (Mulitlevel) = @itchyshin 
- [x] Figure 7 (Summary + Recommendation) = @roseodea + @itchyshin 
- [x] Checking related code = @roseodea + @daniel1noble 

### Appnedices
- [x] Appnedix S1 (Survey) = @roseodea 
- [x] Appnedix S2 (Egger to meta-regression) = @itchyshin 
- [x] Appnedix S3 (Fail-safe N) = @itchyshin 
- [x] Appnedix S4 (main worked examples) = @ASanchez-Tojar + @Yefeng0920
- [x] Appnedix S5 (averaging and sampling) = @ASanchez-Tojar + @Yefeng0920
- [x] Checking related code = @roseodea + @daniel1noble 

## Stage 2

- [x] getting approvals from coauthors group 1 (people on this repo)
- [x] emailing coauthor group 2 (Tim, Julia, Micahel)
